package CONFIG is

  OUTPUT_SCREEN_SIZE : INTEGER := 16;

  type CONFIGURATION_TYPE is (DEVELOPER_VERSION, USER_VERSION, MEANINGS); 
                              
  CONFIGURATION : CONFIGURATION_TYPE := DEVELOPER_VERSION;

  type METHOD_TYPE is (INTERACTIVE, COMMAND_LINE_INPUT, COMMAND_LINE_FILES);

  METHOD : METHOD_TYPE := INTERACTIVE;

  SUPPRESS_PREFACE : BOOLEAN := FALSE;   
  
  
end CONFIG;
