with TEXT_IO;
with DICTIONARY_PACKAGE; use DICTIONARY_PACKAGE;
package LIST_PACKAGE is

  SCROLL_LINE_NUMBER : INTEGER := 0;
  OUTPUT_SCROLL_COUNT : INTEGER := 0;

  procedure LIST_STEMS(OUTPUT : TEXT_IO.FILE_TYPE;
                     RAW_WORD : STRING;
                     PPA : in out PARSE_ARRAY; PPA_LAST : in out INTEGER);

  procedure LIST_POSSIBLES(OUTPUT : TEXT_IO.FILE_TYPE; INPUT_WORD : STRING);

end LIST_PACKAGE;